url: http://sudweb.fr
title: Sud Web
description: Les actualités de la conférence web itinérante du sud de la France.
baseurl: /blog
permalink: /:year/:month/:title/
paginate: 5
paginate_path: "/page/:num/"
timezone: Europe/Paris
lang: fr

twitter:
  username: sudweb

logo: assets/images/logo-sudweb.png

editions:
  2016: Bordeaux
  2015: Montpellier
  2014: Toulouse
  2013: Avignon
  2012: Toulouse
  2011: Nîmes

exclude: [vendor, script]

gems:
- jekyll-mentions
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

prose:
    rooturl: '2016/_posts'
    siteurl: 'http://sudweb.fr/blog/'
    relativeLinks: 'http://sudweb.fr/blog/links.jsonp'
    media: 'assets/images'
