repository: sudweb/blog
url: http://sudweb.fr
title: Sud Web
description: Les actualités de la conférence web itinérante du sud de la France.
baseurl: /blog
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page/:num/"
timezone: Europe/Paris

analytics:
    google:
        tracking_id: UA-22076213-1

# jekyll-seo-tag
logo: assets/images/logo-sudweb.png
twitter:
  username: sudweb

editions:
  2016: Bordeaux
  2015: Montpellier
  2014: Toulouse
  2013: Avignon
  2012: Toulouse
  2011: Nîmes

kramdown:
    input: GFM

exclude:
    - vendor
    - script
    - Procfile
    - README.md
    - Gemfile
    - Gemfile.lock

gems:
    - jekyll-mentions
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-github-metadata

prose:
    rooturl: '2016/_posts'
    siteurl: 'http://sudweb.fr/blog/'
    relativeLinks: 'http://sudweb.fr/blog/links.jsonp'
    media: 'assets/images'
