---
title: Le blog de Sud Web
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
description: La conférence super-humaine
url: https://sudweb.fr
repository: sudweb/blog
baseurl: "/blog"
port: 4000
permalink: "/:categories/:title/"
paginate_path: "/page/:num/"
paginate: 5
kramdown:
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
logo: assets/images/logo-sudweb.png
twitter:
  username: sudweb
analytics:
  google:
    tracking_id: UA-22076213-1
prose:
  rooturl: 2017/_posts
  siteurl: https://sudweb.fr/blog/
  relativeLinks: https://sudweb.fr/blog/links.jsonp
  media: assets/images
gems:
- jekyll-feed
- jekyll-github-metadata
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
exclude:
- Gemfile
- Gemfile.lock
- Procfile
- README.md
- script
- vendor
